use case pour controle des reponses consultation
agora-gouv/agora-back pull request #237
Opened 2023-09-22 13:42 UTC by imaneryane

2023-12-04 16:05 UTC, thierrylee commented on src/main/kotlin/fr/gouv/agora/usecase/reponseConsultation/CommunControlQuestionUseCase.kt
> +        response.responseText.length > MAX_TEXT_LENGTH
Pourquoi ne pas avoir une classe abstraite qui prend une question + `ReponseConsultationInserting` et qui renvoi un boolean pour dire si c'est bon ou non ?
J'en suis même pas à la suite mais vu comme c'est fait ça à l'air d'être plutôt galère à utiliser...

2023-12-04 16:06 UTC, thierrylee commented on src/main/kotlin/fr/gouv/agora/usecase/reponseConsultation/ControlResponseConsultationUseCase.kt
> +                    else -> return false
Quelle galère 😱

2023-12-04 16:07 UTC, thierrylee commented on src/test/kotlin/fr/gouv/agora/usecase/reponseConsultation/ControlResponseConsultationUseCaseTest.kt
> +internal class ControlResponseConsultationUseCaseTest {
Du coup je n'ose même pas regarder les tests 🫣

2023-12-05 13:19 UTC, thierrylee requested changes

2023-12-05 13:19 UTC, thierrylee commented on src/main/kotlin/fr/gouv/agora/usecase/reponseConsultation/ControlResponseConsultationUseCase.kt
> +        question: Question?,
Si tu met la question non null ici ça te permettrait d'avoir un `when` exhaustif sans `else` (mieux pour la maintenance)

2023-12-05 13:19 UTC, thierrylee commented on src/main/kotlin/fr/gouv/agora/usecase/reponseConsultation/ResponseQuestionValidator.kt
> +    fun isChoiceIdOverOne(listChoices: List<String>) = listChoices.size > 1
`hasAtLeastOneChoice` ?

2023-12-05 15:32 UTC, imaneryane commented on src/main/kotlin/fr/gouv/agora/usecase/reponseConsultation/ControlResponseConsultationUseCase.kt
> +        question: Question?,
done

2023-12-05 15:37 UTC, imaneryane commented on src/main/kotlin/fr/gouv/agora/usecase/reponseConsultation/ResponseQuestionValidator.kt
> +    fun isChoiceIdOverOne(listChoices: List<String>) = listChoices.size > 1
done

2023-12-05 15:46 UTC, imaneryane commented on src/main/kotlin/fr/gouv/agora/usecase/reponseConsultation/ResponseQuestionValidator.kt
> +        private const val AUTRE_MAX_TEXT_LENGTH = 200
done

2023-12-05 17:11 UTC, imaneryane commented on src/main/kotlin/fr/gouv/agora/usecase/reponseConsultation/ResponseQuestionValidator.kt
> +    fun isChoiceAutreOverMaxLength(response: ReponseConsultationInserting) =
done

2023-12-06 10:39 UTC, imaneryane commented on src/main/kotlin/fr/gouv/agora/usecase/reponseConsultation/ResponseQuestionValidator.kt
> +
done

2023-12-06 10:41 UTC, imaneryane commented on src/main/kotlin/fr/gouv/agora/usecase/reponseConsultation/ResponseQuestionValidator.kt
> +    private fun isTextFieldOverMaxLength(response: ReponseConsultationInserting) =
done

2023-12-06 10:53 UTC, thierrylee commented on src/main/kotlin/fr/gouv/agora/usecase/reponseConsultation/ControlResponseConsultationUseCase.kt
> +            question?.let { responseQuestionValidator?.isValid(question, response) } == true
Autre façon d'écrire que je trouve plus élégante:
```
questionList.find { it.id == response.questionId }?.let { question ->
  getResponseQuestionValidator(question)?.let { validator ->
    responseQuestionValidator.isValid(question, response)
  } ?: false
} ?: false
```

2023-12-06 10:53 UTC, thierrylee commented on src/main/kotlin/fr/gouv/agora/usecase/reponseConsultation/ControlResponseConsultationUseCase.kt
> +                else questionUniqueChoiceAndConditionalValidator
Un `when` ici pour être exhaustif ?

2023-12-06 11:25 UTC, imaneryane commented on src/main/kotlin/fr/gouv/agora/usecase/reponseConsultation/ControlResponseConsultationUseCase.kt
> +                else questionUniqueChoiceAndConditionalValidator
done

2023-12-06 11:31 UTC, imaneryane commented on src/main/kotlin/fr/gouv/agora/usecase/reponseConsultation/ControlResponseConsultationUseCase.kt
> +            question?.let { responseQuestionValidator?.isValid(question, response) } == true
done

2023-12-06 16:08 UTC, thierrylee commented on src/main/kotlin/fr/gouv/agora/usecase/reponseConsultation/ControlResponseConsultationUseCase.kt
> +            else -> null
J'arrive à être exhaustif de cette façon:
```
return when (question) {
            is QuestionMultipleChoices -> questionMultipleChoicesValidator
            is QuestionUniqueChoice -> questionUniqueChoiceAndConditionalValidator
            is QuestionConditional -> questionUniqueChoiceAndConditionalValidator
            is QuestionWithChoices -> null
            is QuestionOpen -> questionOpenValidator
            is QuestionChapter -> null
            null -> null
        }
```

2023-12-06 16:08 UTC, thierrylee commented on src/test/kotlin/fr/gouv/agora/usecase/reponseConsultation/ControlResponseConsultationUseCaseTest.kt
> +            )
Tu peux mettre cette partie dans un `@Before` spécifique à `QuestionOpenTestCases`
Idem pour les autres typologies de questions

2023-12-06 16:12 UTC, imaneryane commented on src/main/kotlin/fr/gouv/agora/usecase/reponseConsultation/ControlResponseConsultationUseCase.kt
> +            else -> null
done

2023-12-06 22:01 UTC, imaneryane commented on src/test/kotlin/fr/gouv/agora/usecase/reponseConsultation/ControlResponseConsultationUseCaseTest.kt
> +            )
done

2023-12-07 08:29 UTC, thierrylee commented on src/main/kotlin/fr/gouv/agora/infrastructure/reponseConsultation/ReponseConsultationController.kt
> +        return if (!controlResponseConsultationUseCase.isResponseConsultationValid(
L'appel au useCase doit se faire dans la task !! 🚨

2023-12-07 10:02 UTC, merged