ajouter règles pour récupération feedbackResults
agora-gouv/agora-back pull request #301
Opened 2023-10-20 13:41 UTC by imaneryane

2023-10-20 13:56 UTC, thierrylee requested changes

2023-10-20 13:56 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/feedbackQag/FeedbackQagController.kt
> +                    ResponseEntity.ok().body(mapper.toJson(qagResult.qag, userId = userId).response?.feedbackResults)
3 choses:
- à conditionner avec le featureFlag
- faire le calcul uniquement en cas de Success
- pas possible de faire le calcul des résultats de feedback sans recréer complètement la QaG ?

2023-10-20 16:33 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/usecase/feedbackQag/InsertFeedbackQagUseCase.kt
> +                else FeedbackQagListResult.Success(null)
Mieux vaut faire des `Success` différents

2023-10-23 11:08 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/usecase/feedbackQag/InsertFeedbackQagUseCase.kt
> +                else FeedbackQagListResult.Success(null)
done mais je ne suis pas trop sûre du nom :(

2023-10-23 13:40 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/feedbackQag/FeedbackQagController.kt
> +                        .body("")
En théorie, plus besoin de ce if/else

2023-10-23 13:40 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/usecase/feedbackQag/InsertFeedbackQagUseCase.kt
> +    object FeedbackDisabled : FeedbackQagListResult()
`SuccessNoFeedback` ou `SuccessFeedbackDisabled`, il faut quand même qu'on ait cette notion de Success

2023-10-23 13:40 UTC, thierrylee commented on src/test/kotlin/fr/social/gouv/agora/usecase/feedbackQag/InsertFeedbackQagUseCaseTest.kt
> +        then(getFeedbackQagRepository).should(times(1)).getFeedbackQagList(qagId = "qagId")
C'est mieux de mettre des `only` que des `times`

2023-10-23 14:50 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/usecase/feedbackQag/InsertFeedbackQagUseCase.kt
> +    object FeedbackDisabled : FeedbackQagListResult()
done

2023-10-23 16:04 UTC, thierrylee approved these changes

2023-10-23 16:05 UTC, merged