ajout du message temporaire dans GetConsultationFinishedPaginatedList…
agora-gouv/agora-back pull request #359
Opened 2023-12-19 13:54 UTC by imaneryane

…UseCase

2023-12-19 14:09 UTC, thierrylee requested changes

2023-12-19 14:09 UTC, thierrylee commented on src/main/kotlin/fr/gouv/agora/usecase/consultationUpdate/ConsultationUpdateUseCase.kt
> +    fun generateTemporaryConsultationUpdate(consultationUpdate: ConsultationUpdate?): ConsultationUpdate? {
Plutôt que mettre cette méthode en public, je ferai une méthode: 
`getConsultationUpdates(consultationInfos: List<ConsultationInfo>): List<ConsultationUpdate>`

Ensuite il faudrait que:
- `ConsultationListUseCase` appelle cette nouvelle méthode
- `GetConsultationFinishedPaginatedListUseCase` n'ait pas besoin d'être changée

Et comme on s'était dit, supprimer `GetConsultationPreviewFinishedListUseCase` (et probablement onGoing + answered)

2023-12-19 15:42 UTC, imaneryane commented on src/main/kotlin/fr/gouv/agora/usecase/consultationUpdate/ConsultationUpdateUseCase.kt
> +    fun generateTemporaryConsultationUpdate(consultationUpdate: ConsultationUpdate?): ConsultationUpdate? {
c'est bon pour suppression des use case GetConsultationPreviewFinishedListUseCase et GetConsultationPreviewOngoingListUseCase. J'ai mis à jour ConsultationUpdateUseCase, mais je ne vois pas comment utiliser cette méthode: getConsultationUpdates(consultationInfos: List<ConsultationInfo>): List<ConsultationUpdate>

2023-12-20 08:30 UTC, thierrylee commented on src/main/kotlin/fr/gouv/agora/usecase/consultation/ConsultationListUseCase.kt
> +            val consultationUpdate = consultationUpdateUseCase.getConsultationUpdate(consultationInfo)
Plutôt que de récupérer les consultationUpdate une à une ici, tu peux les récupérer en batch avec la nouvelle méthode que tu as créée, ce sera beaucoup plus efficient

2023-12-20 08:30 UTC, thierrylee commented on src/main/kotlin/fr/gouv/agora/usecase/consultationPaginated/GetConsultationFinishedPaginatedListUseCase.kt
> +                    consultationUpdateUseCase.getConsultationUpdate(consultationPreviewFinishedInfo)?.let {
Maintenant qu'elle existe, on peut aussi récupérer les consultationUpdate en batch ici

2023-12-20 10:10 UTC, imaneryane commented on src/main/kotlin/fr/gouv/agora/usecase/consultationPaginated/GetConsultationFinishedPaginatedListUseCase.kt
> +                    consultationUpdateUseCase.getConsultationUpdate(consultationPreviewFinishedInfo)?.let {
done

2023-12-20 10:10 UTC, imaneryane commented on src/main/kotlin/fr/gouv/agora/usecase/consultation/ConsultationListUseCase.kt
> +            val consultationUpdate = consultationUpdateUseCase.getConsultationUpdate(consultationInfo)
done

2023-12-20 10:16 UTC, thierrylee commented on src/main/kotlin/fr/gouv/agora/usecase/consultationPaginated/GetConsultationFinishedPaginatedListUseCase.kt
>              thematiqueRepository.getThematique(consultationPreviewFinishedInfo.thematiqueId)
Désolé je le vois que maintenant, mais ce serait mieux de faire un traitement similaire pour les thématiques: les récupérer en batch puis faire un find => mieux optimisé

2023-12-20 11:02 UTC, thierrylee approved these changes

2023-12-20 11:05 UTC, merged